language: php
sudo: false
php:
  - "7.1"
env:
  global:
    - CC_TEST_REPORTER_ID=26d568631c25956b1f310179c462b72201fa938263bb027ef38f9f0db8939d1a
install:
  - composer install
  - composer dump-autoload -o
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
